# Book settings
title: Repositorio Principios de Optimización
author: Equipo Principios de Optimización
logo: logo-uniandes.png

latex:
  latex_documents:
    targetname: book.tex

html:
  favicon: icon.png
  home_page_in_navbar: false

parse:
  myst_extended_syntax: true
