# Book settings
title: Repositorio Principios de Optimización
author: Equipo Principios de Optimización
logo: _static/logo-uniandes.png

repository:
  url: https://github.com/copa-uniandes/optimizacion
  path_to_book: ./optimizacion/
  branch: master

launch_buttons:
  notebook_interface: "classic"
  binderhub_url: "https://mybinder.org/v2/gh/copa-uniandes/optimizacion/master"
  thebe: true

latex:
  latex_documents:
    targetname: book.tex

html:
  favicon: _static/icon.png
  home_page_in_navbar: false
  use_repository_button: true
  use_issues_button: true

parse:
  myst_extended_syntax: true
