# Book settings
title: Repositorio Principios de Optimización
author: Equipo Principios de Optimización
logo: _static/logo-uniandes.png

latex:
  latex_documents:
    targetname: book.tex

html:
  favicon: _static/icon.png
  home_page_in_navbar: false

parse:
  myst_extended_syntax: true
